#!/bin/bash

###########################
## USAGE:
## ./run 1 : Seed and run
## ./run : Just run
## 
## For java components:
## CodehubAutoSolveTable [delay to run, in sec] [delay between updates, in min] [SQL user] [SQL pass]
###########################

SQL_USER="homestead";
SQL_PASS="secret";

javac -cp .:./mysql-connector-java-5.1.40-bin.jar *.java; 

#Seeding the userproblemscore table
if [[ $1 -eq 1 ]]
then
	echo "== Running userproblemscore table seeder... =="
	java -cp .:./mysql-connector-java-5.1.40-bin.jar CodehubSeederScoreTable $SQL_USER $SQL_PASS
	echo "== DONE =="
fi

#Auto update problemsolvingresult table
PROCESS_NUM=$(ps -ef | grep "CodehubAutoSolveTable" | grep -v "grep" | wc -l)
if [[ $PROCESS_NUM -lt 1 ]]
then
	(java -cp .:./mysql-connector-java-5.1.40-bin.jar CodehubAutoSolveTable 0 10 $SQL_USER $SQL_PASS) &
else
	echo "CodehubAutoSolveTable: already run!";
fi

#Auto update rankingtable
PROCESS_NUM_1=$(ps -ef | grep "CodehubAutoRankingTable" | grep -v "grep" | wc -l)
if [[ $PROCESS_NUM_1 -lt 1 ]]
then
	(java -cp .:./mysql-connector-java-5.1.40-bin.jar CodehubAutoRankingTable 30 15 $SQL_USER $SQL_PASS) &
else
	echo "CodehubAutoRankingTable: already run!";
fi

echo "ALL DONE!";

